name: package-getting-started-app
on : [push]
jobs: 
  package-getting-started-app:
    runs-on: ubuntu-latest
    steps:
    #checkout le code
      - name: Checkout code
      - uses: actions/checkout@v2
      - run: tree
        
# checkout le code
# build et tag image
# push sur dockerhub
