name: package-getting-started-app
on : [push]
jobs: 
  package-getting-started-app:
    runs-on: ubuntu-latest
    steps:
    #checkout le code
      - name: Checkout code
        uses: actions/checkout@v2
      - run: tree
        name: Run
        
      - name: Build/Push Docker Img
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kevlb29/getting-started-app:latest
          
# checkout le code
# build et tag image
# push sur dockerhub
