#Lorsqu'un push survient, on veut automatiquelebt créer une image docker et la pousser sur le dockerhub.

#Trigger
#lorsqu'un push survient

#Steps :
# - checkout le code
# - build et tag image
# - docker login
# - push sur dockerhub

#Bonus
# - Gérer les secrets (username / password / token) de manière sécurisée.

name: package-getting-started-app
on : [push]
jobs: 
  package-getting-started-app:
    runs-on: ubuntu-latest
    steps:
    #checkout le code
      - name: Checkout code
        uses: actions/checkout@v2
      - run: tree
        name: Run
    #login docker
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      #- run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
    #build et tag image
      - name: Build/Push Docker Img
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kevlb29/getting-started-app:latest

    
          
